package com.ichunming.banjia.model;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Integer viewCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.title
	 * @return  the value of article.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.title
	 * @param title  the value for article.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.view_cnt
	 * @return  the value of article.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Integer getViewCnt() {
		return viewCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.view_cnt
	 * @param viewCnt  the value for article.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setViewCnt(Integer viewCnt) {
		this.viewCnt = viewCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.create_date
	 * @return  the value of article.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.create_date
	 * @param createDate  the value for article.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.content
	 * @return  the value of article.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.content
	 * @param content  the value for article.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}