package com.ichunming.banjia.model;

import java.util.Date;

public class Introduce {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.uid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Long uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.pics
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String pics;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Integer viewCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.update_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column introduce.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.id
	 * @return  the value of introduce.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.id
	 * @param id  the value for introduce.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.uid
	 * @return  the value of introduce.uid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Long getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.uid
	 * @param uid  the value for introduce.uid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setUid(Long uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.title
	 * @return  the value of introduce.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.title
	 * @param title  the value for introduce.title
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.pics
	 * @return  the value of introduce.pics
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getPics() {
		return pics;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.pics
	 * @param pics  the value for introduce.pics
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setPics(String pics) {
		this.pics = pics == null ? null : pics.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.view_cnt
	 * @return  the value of introduce.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Integer getViewCnt() {
		return viewCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.view_cnt
	 * @param viewCnt  the value for introduce.view_cnt
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setViewCnt(Integer viewCnt) {
		this.viewCnt = viewCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.create_date
	 * @return  the value of introduce.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.create_date
	 * @param createDate  the value for introduce.create_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.update_date
	 * @return  the value of introduce.update_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.update_date
	 * @param updateDate  the value for introduce.update_date
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column introduce.content
	 * @return  the value of introduce.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column introduce.content
	 * @param content  the value for introduce.content
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}