package com.ichunming.banjia.model;

public class Location {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.pid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.name
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.id
	 * @return  the value of location.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.id
	 * @param id  the value for location.id
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.pid
	 * @return  the value of location.pid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.pid
	 * @param pid  the value for location.pid
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.name
	 * @return  the value of location.name
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.name
	 * @param name  the value for location.name
	 * @mbggenerated  Thu Mar 09 16:42:34 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}