package com.ichunming.banjia.model;

import java.util.Date;

public class Promote {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.id
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.uid
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.pic
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.effect_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    private Date effectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promote.expire_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    private Date expireDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.id
     *
     * @return the value of promote.id
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.id
     *
     * @param id the value for promote.id
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.uid
     *
     * @return the value of promote.uid
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.uid
     *
     * @param uid the value for promote.uid
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.pic
     *
     * @return the value of promote.pic
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.pic
     *
     * @param pic the value for promote.pic
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.effect_date
     *
     * @return the value of promote.effect_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public Date getEffectDate() {
        return effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.effect_date
     *
     * @param effectDate the value for promote.effect_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public void setEffectDate(Date effectDate) {
        this.effectDate = effectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promote.expire_date
     *
     * @return the value of promote.expire_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promote.expire_date
     *
     * @param expireDate the value for promote.expire_date
     *
     * @mbggenerated Thu Mar 09 17:57:09 CST 2017
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }
}