package com.ichunming.banjia.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.role
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private Integer role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.portrait
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private String portrait;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.address
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
	 * @return  the value of user.mobile
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
	 * @param mobile  the value for user.mobile
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.role
	 * @return  the value of user.role
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.role
	 * @param role  the value for user.role
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.portrait
	 * @return  the value of user.portrait
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public String getPortrait() {
		return portrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.portrait
	 * @param portrait  the value for user.portrait
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setPortrait(String portrait) {
		this.portrait = portrait == null ? null : portrait.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.address
	 * @return  the value of user.address
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.address
	 * @param address  the value for user.address
	 * @mbggenerated  Thu Mar 09 17:40:30 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}
}