package com.ichunming.banjia.model;

public class UserType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_type.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_type.tid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_type.uid
     *
     * @return the value of user_type.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_type.uid
     *
     * @param uid the value for user_type.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_type.tid
     *
     * @return the value of user_type.tid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_type.tid
     *
     * @param tid the value for user_type.tid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}