package com.ichunming.banjia.model;

public class UserLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_location.lid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    private Integer lid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.uid
     *
     * @return the value of user_location.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.uid
     *
     * @param uid the value for user_location.uid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_location.lid
     *
     * @return the value of user_location.lid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_location.lid
     *
     * @param lid the value for user_location.lid
     *
     * @mbggenerated Thu Mar 09 16:31:38 CST 2017
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }
}